Models/Context.cs
using Microsoft.EntityFrameworkCore;
using SurveySystem.ViewModel;

namespace SurveySystem.Models
{
    public class Context:DbContext
    {
        public DbSet<Department> Departments { get; set; }
        public DbSet<TblKPI> KPIs { get; set; }
        public Context():base()
        { }
        public Context(DbContextOptions options) : base(options)
        { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblKPI>(t => t.Property(a => a.MeasurementUnit).HasColumnType("Bit"));
        }
        public DbSet<SurveySystem.ViewModel.KPIVM> KPIVM { get; set; } = default!;
    }
}

Models/Department.cs
namespace SurveySystem.Models
{
    public class Department
    {
        public int Id {  get; set; }
        public string Name { get; set; }
        public List<TblKPI>? tblKPIs { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace SurveySystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TblKPI .cs
using DataAnnotationsExtensions;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SurveySystem.Models
{
    public class TblKPI
    {
        [Key]
        [Display(Name ="Indicator Num")]
        public int KPIDNum { get; set; }

        [Column(TypeName = "nvarchar(150)")]
        public string Description { get; set; }
        [Display(Name = "Measurement Unit")]

        public bool MeasurementUnit { get; set; }
        [Display(Name = "Target Value")]

        public int TargetValue { get; set; }
        [ForeignKey("Department")]
        [Display(Name = "Department")]

        public int DepNO { get; set; }
        public Department? Department { get; set; }

    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SurveySystem.Contract;
using SurveySystem.Models;
using System.Runtime.CompilerServices;

namespace SurveySystem.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository departmentRepository;

        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            this.departmentRepository = departmentRepository;
        }
        public IActionResult Index()
        {
            var depts =departmentRepository.GetAll();
            return View(depts);
        }
        public IActionResult Details(int id)
        {
            var dept =departmentRepository.GetById(id);
            return View(dept);
        }
    
     
        public IActionResult Edit(int id)
        {
            var dept = departmentRepository.GetById(id);
            return View(dept);
        }
        [HttpPost]
     
        public IActionResult Edit(int id ,Department department)
        {
            if (ModelState.IsValid)
            {
                departmentRepository.Update(id, department);
               return RedirectToAction("Index");
            }
           
                return View(department);
            
        }
        public IActionResult Delete(int id)
        {
            var item =departmentRepository.GetById(id); 
            if (item != null)
            {
                departmentRepository.Delete(id);
            }
            return RedirectToAction("Index");                           

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid )
            {
                departmentRepository.Insert(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SurveySystem.Models;
using System.Diagnostics;

namespace SurveySystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TblKPIController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SurveySystem.Contract;
using SurveySystem.Infrastructure;
using SurveySystem.Models;
using SurveySystem.ViewModel;

namespace SurveySystem.Controllers
{
    public class TblKPIController : Controller
    {
        private readonly ITbIKPIRepository _TbIKPIRepository;
        private readonly IDepartmentRepository departmentRepository;

        public TblKPIController(ITbIKPIRepository _TbIKPIRepository, IDepartmentRepository departmentRepository)
        {
            this._TbIKPIRepository = _TbIKPIRepository;
            this.departmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {
            var items= _TbIKPIRepository.GetAll();
            TempData["total"] = _TbIKPIRepository.gettotal(items);

            return View(items);

        }
        public IActionResult Details(int id)
        {
            var item = _TbIKPIRepository.GetById(id);
            return View(item);
        }
        public IActionResult Delete(int id)
        {
            _TbIKPIRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {
            ViewBag.dept=departmentRepository.GetAll();
            return View();
        }
        
        
        [HttpPost]
        public IActionResult Create(TblKPI tblKPI)
        {
            if (ModelState.IsValid)
            {
                if (tblKPI.MeasurementUnit == false)
                {
                    List<TblKPI> list = _TbIKPIRepository.GetByDeptId(tblKPI.DepNO);
                    double sum = 0,sumnum=0;

                    foreach(var item in list)

                    {
                        if(item.MeasurementUnit == false)
                        sum += item.TargetValue;
                        else sumnum += item.TargetValue;
                    }
                    if (sum + tblKPI.TargetValue > 100)
                    {
                        ModelState.AddModelError("TargetValue", "The Targeted Values of  the “percentage”  indicator KPI should not be more 100% for on department");
                        ViewBag.dept = departmentRepository.GetAll();

                        return View(tblKPI);

                    }
                    else if (sumnum==0)
                    {
                        ModelState.AddModelError("MeasurementUnit", "there is no kpi in this department ,the target value of the first KPI  should be  number");
                        ViewBag.dept = departmentRepository.GetAll();

                        return View(tblKPI);
                    }
                    else
                    {
                        _TbIKPIRepository.Insert(tblKPI);
                        return RedirectToAction("Index");
                    }
                }
                _TbIKPIRepository.Insert(tblKPI);
                return RedirectToAction("Index");
            }
            ViewBag.dept = departmentRepository.GetAll();

            return View(tblKPI);
        }
        public IActionResult Edit(int id)
        {
             var item =   _TbIKPIRepository.GetById(id);
            ViewBag.dept = departmentRepository.GetAll();

            return View(item);
        }
        [HttpPost]
        public IActionResult Edit(int id, TblKPI tblKPI)
        {
            if(ModelState.IsValid)
            {
                _TbIKPIRepository.Update(id, tblKPI);
                return RedirectToAction("Index");
            }
            return View(tblKPI); ;
        }
        public IActionResult GetByDeptId(int deptid)
        {
            var items = _TbIKPIRepository.GetByDeptId(deptid);
           
            TempData["total"] = _TbIKPIRepository.gettotal(items);
            return PartialView("_KPIList",items);

        }
        
        

    }


      
   
    
}

Views/Department/Create.cshtml
@model SurveySystem.Models.Department

@{
    ViewData["Title"] = "Create";
}

<div class="row justify-content-center mt-5">
    <div class="col-md-6">
        <form class="px-2" style="box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);" asp-action="Create">
            <h3>Create New Department</h3>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="my-2 form-group">
                <div class="row">
                    <div class="col-3">
                <label asp-for="Name" class="control-label"></label>
                    </div>
                    <div class="col-9">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
                </div>
            </div>
            <div class="row justify-content-center form-group">
                <input type="submit" value="Create" class=" col-2 btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Department/Details.cshtml
@model SurveySystem.Models.Department

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Department/Edit.cshtml
@model SurveySystem.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" >
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input type="submit" value="Save" class="btn btn-primary" />
               
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Department/Index.cshtml
@model IEnumerable<SurveySystem.Models.Department>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SurveySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SurveySystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <!-- Include SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

    <!-- Include SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    <!-- Add this to your _Layout.cshtml -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <style>
        body {
            background-color: rgb(222,240,243);
        }
    </style>
</head>
<body>
    <header style="height:50px;background-color: rgb(7,40,59);">
       @*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SurveySystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
                <h2 style="color: white;text-align: center;" >Servey System </h2>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SurveySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TblKPI/Create.cshtml
@model SurveySystem.Models.TblKPI
@{
    ViewData["Title"] = "Create";
  SelectList list = new SelectList(ViewBag.dept, "Id", "Name");

}


<div class="row justify-content-center mt-5">
    <div class="col-md-6">
        <form class="px-2" style="box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);" asp-action="Create">
            <h3>Create New KPI</h3>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="my-2 form-group">
                <div class="row" >
                    <div class="col-3">

                <label asp-for="Description" class="control-label"></label>
                </div>
                    <div class="col-9">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                </div>
            </div>
            
            <div class=" my-2  form-group">
                <div class="row">
                    <div class="col-3">
                <label asp-for="TargetValue" class="control-label"></label>
                    </div>
                    <div class="col-9">
                <input asp-for="TargetValue" class="form-control" />
                <span asp-validation-for="TargetValue" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row my-2  justify-content-center px-3 ">
            <div class="col-2  form-check">
                <input asp-for="MeasurementUnit" class="form-check-input" type="radio" value="true" />
                <label class="form-check-label">Number</label>
            </div>

            <div class="col-2 form-check">
                <input asp-for="MeasurementUnit" class="form-check-input" type="radio" value="false" />
                <label class="form-check-label">Persentage</label>
            </div>
            </div>
            <div class=" my-2  form-group">
                <div class="row">
                    <div class="col-3">
                <label asp-for="DepNO" class="control-label"></label>
                    </div>
                    <div class="col-9">
                <select asp-items="list" asp-for="DepNO" class ="form-control" asp-items="ViewBag.DepNO"></select>
                    </div>
                </div>
            </div>
            <div class=" row justify-content-center form-group">
                <input type="submit" value="Create" class=" col-2  btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TblKPI/Details.cshtml
@model SurveySystem.Models.TblKPI

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TblKPI</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeasurementUnit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeasurementUnit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.KPIDNum">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TblKPI/Edit.cshtml
@model SurveySystem.Models.TblKPI

@{
    ViewData["Title"] = "Edit";
    SelectList list = new SelectList(ViewBag.dept, "Id", "Name");

}

<h1>Edit</h1>

<h4>TblKPI</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="KPIDNum" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MeasurementUnit" /> @Html.DisplayNameFor(model => model.MeasurementUnit)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TargetValue" class="control-label"></label>
                <input asp-for="TargetValue" class="form-control" />
                <span asp-validation-for="TargetValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepNO" class="control-label"></label>
                <select asp-for="DepNO" asp-items="list" class="form-control" asp-items="ViewBag.DepNO"></select>
                <span asp-validation-for="DepNO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TblKPI/Index.cshtml
@model IEnumerable<SurveySystem.Models.TblKPI>

@{
    ViewData["Title"] = "Index";
}



<div class=" container pb-1 px-2" style="background-color:white">
    <div class="mt-4" style="background-color:rgb(239,239,239);height:50px;text-align:center">
        <h2 style="color:rgb(26,51,67)">Key Performance Indicator</h2>
        <hr style="color:yellow;height:3px" />
    </div>
    <div class="m-3 text-center  ">
        <p class=" mx-2" style="display:inline ">Department Num</p>

        <input id="deptid" onkeydown="handleKeyPress(event,this.value)" type="text" />
    </div>
    <div>
        <a asp-action="Create" asp-controller="TblKPI"> <button onclick="goto()" type="button" class="btn btn-secondary btn-sm"><i class="fa-solid fa-circle-plus mx-2"></i>Add New Row</button></a>
    </div>
    <div>
        <partial name="_KPIList" model="Model"></partial>

    </div>
    
    <hr style="color:yellow;height:3px" />
    <div class="row justify-content-center " >
        
        <a asp-action="Create" asp-controller="Department" class="col-2"><button type="button" class="btn btn-primary px-4 btn-sm">New</button></a>
        <div onclick="confirmDelete()" class="col-2"><button type="button" class="btn btn-primary px-4  btn-sm">Delete</button></div>
        <div  class="col-2"><button type="button" class="btn btn-primary px-4  btn-sm">Save</button></div>
        


    </div>


</div>
<script>
    
    function handleKeyPress(event, text) {
        // Check if the pressed key is Enter (keyCode 13)
        if (event.keyCode === 13) {
            // Call your function or perform your action here
            console.log(text);
            

            $.ajax({
                url: "/TblKPI/GetByDeptId?deptid=" + text,
                success: function (result) {
                    // console.log(result);
                    document.getElementById("bla").innerHTML = result;

                }
            });
        }
    }
    function confirmDelete() {
        var dept = document.getElementById("deptid").value;
        console.log(dept)
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this data!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                // Perform your delete action here, like an AJAX request or form submission
                

                window.location.href = '/Department/Delete/'+dept;
            }
        });
    }
</script>

Views/TblKPI/_KPIList.cshtml
@model IEnumerable<SurveySystem.Models.TblKPI>
@{
    Layout = null;
    double x = double.Parse(TempData["total"].ToString());
  
}

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div id="bla" class="container mt-4">
    <table class="table table-striped table-custom">
        <thead >
            <tr >
                    <th>
                        @Html.DisplayNameFor(model => model.KPIDNum)
                    </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MeasurementUnit)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TargetValue)
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.KPIDNum)
                        </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                        <td>
                            @* @Html.DisplayFor(modelItem => item.MeasurementUnit) *@
                        @if (item.MeasurementUnit == true)
                        {
                            <div class="row">
                                <div class="col">

                                    <input onclick="numtoper(@x,@item.KPIDNum,@item.TargetValue)" type="radio" id="per" name="mu+@item.KPIDNum" value="per">
                                    <label for="per">Pecentage</label>
                                </div>
                                <div class="col">
                                    <input onclick="returntonum(@item.KPIDNum,@item.TargetValue)" checked type="radio" id="num" name="mu+@item.KPIDNum" value="num">
                                    <label for="num">Number</label>
                                </div>
                            </div>
                        }

                        else
                        {
                            <div class="row">
                                <div class="col">
                                    <input onclick="returntoper(@item.KPIDNum,@item.TargetValue)" checked type="radio" id="per" name="mu+@item.KPIDNum" value="per">
                                    <label for="per">Pecentage</label>
                                </div>
                                <div class="col">
                                    <input onclick="pertonum(@x,@item.KPIDNum,@item.TargetValue)" type="radio" id="num" name="mu+@item.KPIDNum" value="num">
                                    <label for="num">Number</label>
                                </div>
                            </div>

                        }

                        </td>
                        <td id="cell+@item.KPIDNum" >
                            @Html.DisplayFor(modelItem => item.TargetValue)

                            @if (item.MeasurementUnit != true)
                            {
                                <span>%</span>
                            }

                        </td>


                    </tr>
                }
            </tbody>
        </table>
    
        <div class=" row justify-content-end">
            <p class ="col-1">Total:</p>
        <label style="background-color:#A6A6A6;border-block-color:black;border-block:solid" class="col-3 mx-3 ">@x</label>
        </div>
    </div>
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f5f5f5;
        padding-top: 20px;
    }

    #bla {
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        padding: 20px;
        margin-top: 20px;
    }

    .table-custom {
        background-color: #ffffff;
    }

        .table-custom thead th {
            background-color: #07283B;
            color: #ffffff;
        }

        .table-custom tbody tr:nth-child(odd) {
            background-color: #f2f2f2;
        }

        .table-custom tbody tr:nth-child(even) {
            background-color: #cccccc;
        }

    .form-check label {
        margin-left: 5px;
    }

    .btn-primary {
        background-color: #3498db;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background-color: #2184c4;
        }

    a {
        color: #3498db;
        text-decoration: none;
        display: inline-block;
        margin-top: 10px;
    }
</style>
    <script>
        function returntonum(id, value) {

            var c = document.getElementById("cell+" + id)
           
                c.innerHTML = value

        }
        
        function returntoper(id, value) {

            var c = document.getElementById("cell+" + id)

            c.innerHTML = value+"%"

        }
        function numtoper(total,id,value){
          
           var c= document.getElementById("cell+"+id)
           var per = ((value / total) * 100);
            var y;
            if (per % 1 === 0) {
                y = per

            }else{
                y = per.toFixed(3)

            }
            console.log(per)
            c.innerHTML=per+"%"


        }
        function pertonum(total, id, value) {

            var c = document.getElementById("cell+" + id)
            var num = (value/100)*total;
            console.log(num)
            c.innerHTML =num.toString()
        }
        
    </script>

    